#!/bin/bash

#Name       : cleanup.sh
#Arguments  : None
#Details    : To perform clean up of files generated by the program.
#Author     : Sanket Chandorkar

cd ..

rm -rf log
mkdir log

cd scripts

echo "  Clean up done !!" 